version: '3.8'
services:
  frontend:
    build:
      context: ./frontend  # Point to the frontend folder
      dockerfile: Dockerfile.dev  # Specify the development Dockerfile
    ports:
      - "3000:3000"  # Map port 3000 in the container to port 3000 on your host machine
    volumes:
      - ./frontend:/app  # Mount the frontend folder to /app in the container
      - /app/node_modules  # Prevent the node_modules folder from being overwritten
    environment:
      NODE_ENV: development  # Set the environment variable to development
    command: npm run dev  # Run the Next.js app in development mode
